vo=gpu-next
# hwdec=auto-safe
hwdec=vulkan
hwdec-codecs=all

gpu-api=vulkan
gpu-context=waylandvk
# hwdec=nvdec

scale=ewa_lanczos
no-border

# Use extra large RAM cache (needs cache=yes to make it useful).
cache=yes
demuxer-max-bytes=1024M
demuxer-max-back-bytes=512M

# yt-dl
ytdl-format=bestvideo[vcodec^=avc1]+bestaudio/best
ytdl-raw-options="compat-options=playlist-match-filter,yes-playlist="

# Subtitles
# sub-font='Roboto'
# sub-font='Trebuchet MS'
sub-font='LiterationSans Nerd Font'
sub-auto=fuzzy
# sub-border-size = 3
# sub-shadow-offset = 2
# sub-shadow-color = 0.0/0.0/0.0

display-tags=date,title,synopsis,description,summary,series_page,episode_page

[norm]
profile-desc="Normalize audio volume"
af=lavfi=[loudnorm=I=-18:TP=-1.5:LRA=8]

# [anime]
# profile-desc=Smooth anime content
# profile-cond=get('current-tracks/audio/lang') == 'ja'
# video-sync=display-resample
# interpolation=yes
# # interpolation-threshold=-1
# tscale=mitchell
# tscale-blur=0.65

[hdr]
profile-desc=HDR output (requires GNOME HDR enabled)
vo=gpu-next
gpu-api=vulkan
gpu-context=waylandvk
target-trc=pq
target-prim=bt.2020
target-peak=600
hdr-compute-peak=no
tone-mapping=st2094-40

[hdr-sdr]
profile-desc=Tone map HDR content for SDR display
profile-cond=p["video-params/gamma"]=="pq" or p["video-params/gamma"]=="hlg"
profile-restore=copy
tone-mapping=bt.2446a
gamut-mapping-mode=perceptual
hdr-compute-peak=yes
hdr-peak-percentile=99.995
hdr-contrast-recovery=0.4
target-contrast=inf

[ani]
profile-desc=Smooth animated content
video-sync=display-resample
interpolation=yes
interpolation-threshold=-1
tscale=mitchell
tscale-blur=0.65
