set-option -g default-shell /usr/bin/fish

# Mouse
set-option -g mouse on
bind-key m set-option -g mouse \; display "Mouse: #{?mouse,ON,OFF}"

# Remote color fix
# if terminal not listed, use `echo $TERM` outside tmux
set-option -ga terminal-features 'wezterm:RGB'
set-option -ga terminal-features 'alacritty:RGB'
set-option -ga terminal-features 'xterm-kitty:RGB'
set-option -ga terminal-features 'xterm-ghostty:RGB'
set-option -ga terminal-features 'xterm-256color:RGB'

